### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by jsfan**
* Removed unused code
* Refactored code to make it DRY

As there are no tests, I cannot guarantee that this will not break anything. However, the logic should have been preserved and the output is only different where typos have been corrected.

### CODE REVIEW

**Comment by abhaybhargav** [comment]
Hi @jsfan Thanks for this. Currently, the entire team is busy with training and some deliverables. Will probably have a look at this Nov 2nd week and add to the new rel. We are looking at 1.2 release, with some additional features as well. We also added some minimal tests to that release.

**Comment by jsfan** [comment]
No rush. If I get around to it, I will add some more cleanup and maybe also some tests.

**Comment by abhaybhargav** [comment]
Hi @jsfan - Added multiple changes to Release 1.2 and have updated most of the docs. Could you please include your changes and optimizations to the new codebase? Thanks

**Comment by jsfan** [comment]
@abhaybhargav: Should be ok now.

**Comment by abhaybhargav** [comment]
Thanks @jsfan. Will probably do a little more in terms of tests over this week and add additional bugfixes. I have currently observed some issues with the cli

**Comment by jsfan** [comment]
No worries. I'll see if I can contribute some more cleanup soon.

**Comment by abhaybhargav** [comment]
👍

**Pull request merged**
